name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build application
        run: npm run build

      - name: Start application in production mode
        run: npm run start-prod &
        env:
          NODE_ENV: production

      - name: Wait for server to start
        run: npx wait-on http://localhost:5000

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          wait-on: http://localhost:5000

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: |
          curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}

  tag_release:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: false
          TAG_NAME: "v1.0.0"
          VERSION_TYPE: "patch"

  notify:
    runs-on: ubuntu-20.04
    needs: simple_deployment_pipeline
    if: ${{ always() }} # Runs regardless of success or failure
    steps:
      - name: Notify Discord (Deployment Success)
        if: ${{ steps.trigger_deploy.conclusion == 'success' }}
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          title: A new version of Pokedex deployed!
          status: Success
          color: 0x00ff00
          description: "Commit [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}) built and deployed to [Production URL](${{ vars.DEPLOYMENT_URL }})!"
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Github Actions

      - name: Notify Discord (Build Failure)
        if: ${{ failure() }}
        uses: sarisia/actions-status-discord@v1.15.0
        with:
          title: Build failed
          status: Failure
          color: 0xff0000
          description: "Pipeline failed for commit [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})."
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Github Actions
