name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Check style
        run: npm run eslint

      - name: Build application
        run: npm run build

      - name: Start application in production mode
        run: npm run start-prod & # Start the server in the background
        env:
          NODE_ENV: production # Ensure production environment is set

      - name: Wait for server to start
        run: npx wait-on http://localhost:5000 # Wait for the application to be accessible

      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e # Command to run your E2E tests
          wait-on: http://localhost:5000 # Wait until the application is available

      - name: Trigger deployment
        if: ${{ github.event_name == 'push' }}
        run: |
          curl -X POST https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
